#create user 
RUN useradd -g users -G users wchen -u 18998 &&\
    echo "wchen ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers &&\
    echo "su - wchen" >> /root/.bashrc

#install pyenv
RUN cd ~ &&\
    git clone git://github.com/yyuu/pyenv.git .pyenv &&\
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile &&\
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile &&\
    echo 'eval "$(pyenv init -)"' >> ~/.bash_profile &&\
    git clone git://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

#make bash_profile (cudn version according to docker version)
RUN cd ~ &&\
	touch ~/.bash_profile_bash &&\
	echo 'export PATH=/usr/local/nvidia/bin/:$PATH' >> ~/.bash_profile_bash &&\
	echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64' >> ~/.bash_profile_bash &&\
	echo 'export CUDA_HOME=/usr/local/cuda-9.0/' >> ~/.bash_profile_bash &&\
	echo 'export PATH=$PATH:/usr/local/cuda-9.0/bin/:$PATH' >> ~/.bash_profile_bash &&\ 
