#install nessesary command
RUN yum install -y epel-release
RUN yum install -y sudo
RUN yum install -y which
RUN yum install -y vim
RUN yum install -y tmux
RUN yum install -y git

#create user
RUN useradd -g users -G users wchen -u 18998 &&\
    echo "wchen ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers &&\
    echo "su - wchen" >> /root/.bashrc
#Download personal config file
RUN cd ~ &&\
    git clone https://github.com/mangohero1985/vim_config.git &&\
    cd ~/vim_config &&\
    mv .vim ~/ &&\
    mv .vimrc ~/ &&\
    mv .tmux.conf ~/ &&\
    cd ~/.vim/bundle/ &&\
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

#install pyenv
RUN cd ~ &&\
    git clone git://github.com/yyuu/pyenv.git .pyenv &&\
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile &&\
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile &&\
    echo 'eval "$(pyenv init -)"' >> ~/.bash_profile &&\
    git clone git://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

#make bash_profile (cudn version according to docker version)
RUN cd ~ &&\
    touch ~/.bash_profile_gpu &&\
    echo 'export PATH=/usr/local/nvidia/bin/:$PATH' >> ~/.bash_profile_bash &&\
    echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64' >> ~/.bash_profile_bash &&\
    echo 'export CUDA_HOME=/usr/local/cuda-9.0/' >> ~/.bash_profile_bash &&\
    echo 'export PATH=$PATH:/usr/local/cuda-9.0/bin/:$PATH' >> ~/.bash_profile_bash
